services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: nextdashboard
      POSTGRES_HOST_AUTH_METHOD: mypassword